version: '3.5'

services:
  prisma-migrate:
    container_name: prisma-migrate
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: "postgresql://root:root@localhost:5438/mydb?schema=public"
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - 5438:5432
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres: