version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5438:5432
    container_name: db-restaurante-34
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: restaurante-34-api
    environment:
    - DATABASE_URL=postgresql://root:root@postgres/postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:

volumes:
  pg_data: